/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet.index'
import { Route as AuthenticatedWalletWithdrawRouteImport } from './routes/_authenticated/wallet.withdraw'
import { Route as AuthenticatedWalletDepositRouteImport } from './routes/_authenticated/wallet.deposit'
import { Route as AuthenticatedChallengesCreateRouteImport } from './routes/_authenticated/challenges.create'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletWithdrawRoute =
  AuthenticatedWalletWithdrawRouteImport.update({
    id: '/wallet/withdraw',
    path: '/wallet/withdraw',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletDepositRoute =
  AuthenticatedWalletDepositRouteImport.update({
    id: '/wallet/deposit',
    path: '/wallet/deposit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengesCreateRoute =
  AuthenticatedChallengesCreateRouteImport.update({
    id: '/challenges/create',
    path: '/challenges/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/predictions': typeof PredictionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/challenges/create': typeof AuthenticatedChallengesCreateRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/predictions': typeof PredictionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/challenges/create': typeof AuthenticatedChallengesCreateRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/predictions': typeof PredictionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/challenges/create': typeof AuthenticatedChallengesCreateRoute
  '/_authenticated/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/_authenticated/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challenges'
    | '/leaderboard'
    | '/predictions'
    | '/reset-password'
    | '/tournaments'
    | '/profile'
    | '/challenges/create'
    | '/wallet/deposit'
    | '/wallet/withdraw'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/challenges'
    | '/leaderboard'
    | '/predictions'
    | '/reset-password'
    | '/tournaments'
    | '/profile'
    | '/challenges/create'
    | '/wallet/deposit'
    | '/wallet/withdraw'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/challenges'
    | '/leaderboard'
    | '/predictions'
    | '/reset-password'
    | '/tournaments'
    | '/_authenticated/profile'
    | '/_authenticated/challenges/create'
    | '/_authenticated/wallet/deposit'
    | '/_authenticated/wallet/withdraw'
    | '/_authenticated/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PredictionsRoute: typeof PredictionsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TournamentsRoute: typeof TournamentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/withdraw': {
      id: '/_authenticated/wallet/withdraw'
      path: '/wallet/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof AuthenticatedWalletWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/deposit': {
      id: '/_authenticated/wallet/deposit'
      path: '/wallet/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof AuthenticatedWalletDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/create': {
      id: '/_authenticated/challenges/create'
      path: '/challenges/create'
      fullPath: '/challenges/create'
      preLoaderRoute: typeof AuthenticatedChallengesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedChallengesCreateRoute: typeof AuthenticatedChallengesCreateRoute
  AuthenticatedWalletDepositRoute: typeof AuthenticatedWalletDepositRoute
  AuthenticatedWalletWithdrawRoute: typeof AuthenticatedWalletWithdrawRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedChallengesCreateRoute: AuthenticatedChallengesCreateRoute,
  AuthenticatedWalletDepositRoute: AuthenticatedWalletDepositRoute,
  AuthenticatedWalletWithdrawRoute: AuthenticatedWalletWithdrawRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  LeaderboardRoute: LeaderboardRoute,
  PredictionsRoute: PredictionsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TournamentsRoute: TournamentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
